apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-backup-s3
data:
  ROTATION_PERIOD:      # days to keep backups (exclude to stop backups from deleting)
  GPG_KEY:              # exported public gpg key
  GPG_KEY_ID:           # email id used in gpg key generation
  POSTGRES_HOST:        # postgres k8s service hostname
  POSTGRES_DB:          # name of database to backup
  AWS_DEFAULT_REGION:   # aws s3 bucket region
  S3_BUCKET:            # aws s3 bucket name